#!/bin/sh

set -e

exec 2>&1

TEST_LIST="test1 test2 test4 testReplaceExisting test_cast test_charcase test_compare test_deep_copy test_double_serializer test_float test_int_add test_json_pointer test_locale test_null test_parse test_parse_int64 test_printbuf test_set_serializer test_set_value test_visit test_object_iterator"

mkdir build
cd build
cmake ..
make
rm -f libjson-c.so.*.*.*
#ln -s /usr/lib/$(dpkg-architecture -qDEB_HOST_MULTIARCH)/libjson-c.so.*.*.* .
for test in $TEST_LIST; do ./tests/$test > /dev/null; done
